/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rohanbudha
 */
public class EditPersonalDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditPersonalDetails.class.getName());

    /**
     * Creates new form EditPersonalDetails
     */
    public EditPersonalDetails() {
        initComponents();
        this.setResizable(true);
        btnSaveProfile.setUI(new javax.swing.plaf.basic.BasicButtonUI());
        btnSaveProfile.setBorder(null);
        setupNavPanels();
        addPlaceholders();

        java.awt.Container cp = getContentPane();
        javax.swing.JPanel mainPanel = new javax.swing.JPanel(null);
        mainPanel.setBackground(new java.awt.Color(249, 226, 226));
        mainPanel.setPreferredSize(new java.awt.Dimension(480, 520));
        java.awt.Component[] comps = cp.getComponents();
        for (java.awt.Component comp : comps) {
            mainPanel.add(comp);
        }
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(mainPanel);
        scrollPane.setBorder(null);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        setContentPane(scrollPane);

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSaveProfile = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 226, 226));
        setSize(new java.awt.Dimension(480, 520));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Edit Profile");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 420, 35);

        txtFullName.setText("Enter your full name");
        getContentPane().add(txtFullName);
        txtFullName.setBounds(130, 90, 320, 30);

        txtEmail.setText("Enter your email");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(130, 150, 320, 30);

        txtPhoneNumber.setText("Enter your number");
        getContentPane().add(txtPhoneNumber);
        txtPhoneNumber.setBounds(130, 210, 320, 30);

        txtAddress.setText("Enter your address");
        getContentPane().add(txtAddress);
        txtAddress.setBounds(130, 270, 320, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Full Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 100, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 100, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Phone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 210, 100, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Address:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 270, 100, 30);

        btnSaveProfile.setBackground(new java.awt.Color(51, 51, 255));
        btnSaveProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSaveProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveProfile.setText("Save Profile");
        getContentPane().add(btnSaveProfile);
        btnSaveProfile.setBounds(30, 400, 190, 35);

        btnCancel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCancel.setText("Cancel");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(260, 400, 190, 35);

        jLabel1.setBackground(new java.awt.Color(249, 226, 226));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
private void setupNavPanels() {
    Object[][] nav = {
    };
    for (Object[] row : nav) {
        javax.swing.JPanel  panel  = (javax.swing.JPanel)  row[0];
        javax.swing.JButton button = (javax.swing.JButton) row[1];
        javax.swing.JLabel  icon   = (javax.swing.JLabel)  row[2];
        java.awt.event.MouseAdapter ma = new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                button.doClick();
            }
            public void mouseEntered(java.awt.event.MouseEvent e) {
                panel.setBackground(new java.awt.Color(180, 230, 230));
            }
            public void mouseExited(java.awt.event.MouseEvent e) {
                panel.setBackground(new java.awt.Color(240, 251, 251));
            }
        };
        panel.addMouseListener(ma);
        icon.addMouseListener(ma);
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
}

private void addPlaceholders() {
    addPlaceholder(txtFullName, "Enter your full name");
    addPlaceholder(txtEmail, "Enter your email");
    addPlaceholder(txtPhoneNumber, "Enter your number");
    addPlaceholder(txtAddress, "Enter your address");
}

private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
    field.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    field.setText(placeholder);
    field.setForeground(new java.awt.Color(180, 180, 180));
    field.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(new java.awt.Color(30, 30, 30));
            }
        }
        public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(new java.awt.Color(180, 180, 180));
            }
        }
    });
}

@Override
public java.awt.Dimension getPreferredSize() {
    return new java.awt.Dimension(480, 520);
}

public javax.swing.JButton getSaveProfileButton() {
    return btnSaveProfile;
}

public javax.swing.JButton getCancelButton() {
    return btnCancel;
}

public javax.swing.JTextField getFullNameField() {
    return txtFullName;
}

public javax.swing.JTextField getEmailField() {
    return txtEmail;
}

public javax.swing.JTextField getPhoneNumberField() {
    return txtPhoneNumber;
}

public javax.swing.JTextField getAddressField() {
    return txtAddress;
}
}
