/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author 
 */
public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form loginpage
     */
    public LoginPage() {
        initComponents();
        txtPassword.setEchoChar('•');
        addPlaceholders(); 
        
        // Programmatic password toggle listener
        btnTogglePassword.addActionListener(e -> {
            if (btnTogglePassword.isSelected()) {
                txtPassword.setEchoChar((char) 0);  // show password
            } else {
                txtPassword.setEchoChar('•');  // hide password
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        comboRole = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnForgotPassword = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        panelPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnTogglePassword = new javax.swing.JToggleButton();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(null);

        panelForm.setBackground(new java.awt.Color(249, 226, 226));
        panelForm.setLayout(null);

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "Admin", "Teacher", "Student" }));
        panelForm.add(comboRole);
        comboRole.setBounds(190, 280, 250, 30);

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        panelForm.add(btnLogin);
        btnLogin.setBounds(110, 350, 330, 23);

        jLabel2.setBackground(new java.awt.Color(249, 226, 226));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Welcome Back");
        panelForm.add(jLabel2);
        jLabel2.setBounds(140, 40, 280, 50);

        jLabel3.setBackground(new java.awt.Color(249, 226, 226));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Sign in to your account");
        panelForm.add(jLabel3);
        jLabel3.setBounds(150, 100, 290, 30);

        jLabel4.setBackground(new java.awt.Color(249, 226, 226));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel4.setText("Email or ID");
        panelForm.add(jLabel4);
        jLabel4.setBounds(40, 180, 110, 21);

        jLabel8.setBackground(new java.awt.Color(249, 226, 226));
        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel8.setText("Role");
        panelForm.add(jLabel8);
        jLabel8.setBounds(40, 290, 100, 21);

        jLabel10.setBackground(new java.awt.Color(249, 226, 226));
        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel10.setText("Don't have an account?");
        panelForm.add(jLabel10);
        jLabel10.setBounds(180, 420, 160, 30);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel11.setText("Password");
        panelForm.add(jLabel11);
        jLabel11.setBounds(40, 230, 110, 23);

        btnForgotPassword.setBackground(new java.awt.Color(249, 226, 226));
        btnForgotPassword.setText("Forgot Password?");
        btnForgotPassword.setBorder(null);
        btnForgotPassword.setBorderPainted(false);
        btnForgotPassword.setContentAreaFilled(false);
        btnForgotPassword.setFocusPainted(false);
        panelForm.add(btnForgotPassword);
        btnForgotPassword.setBounds(200, 390, 150, 17);

        btnRegister.setBackground(new java.awt.Color(249, 226, 226));
        btnRegister.setForeground(new java.awt.Color(0, 51, 255));
        btnRegister.setText("Register");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        btnRegister.setFocusPainted(false);
        panelForm.add(btnRegister);
        btnRegister.setBounds(340, 420, 70, 30);

        panelPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtPassword.setBorder(null);

        btnTogglePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye-open.png"))); // NOI18N
        btnTogglePassword.setBorder(null);
        btnTogglePassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye-close.png"))); // NOI18N

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTogglePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTogglePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelForm.add(panelPassword);
        panelPassword.setBounds(190, 230, 250, 30);

        txtEmail.setText(" Enter email or ID");
        txtEmail.setBorder(null);
        panelForm.add(txtEmail);
        txtEmail.setBounds(190, 180, 250, 30);

        jLabel9.setText("jLabel9");
        panelForm.add(jLabel9);
        jLabel9.setBounds(410, 240, 30, 17);

        panelMain.add(panelForm);
        panelForm.setBounds(230, -10, 520, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ellipse 21.png"))); // NOI18N
        panelMain.add(jLabel1);
        jLabel1.setBounds(50, 90, 130, 110);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Student ");
        panelMain.add(jLabel5);
        jLabel5.setBounds(60, 210, 120, 60);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Management");
        panelMain.add(jLabel6);
        jLabel6.setBounds(30, 250, 160, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("System");
        panelMain.add(jLabel7);
        jLabel7.setBounds(70, 290, 89, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JToggleButton btnTogglePassword;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
private void addPlaceholders() {
    addPlaceholder(txtEmail, "Enter Email or ID");
    addPasswordPlaceholder(txtPassword, "Enter Password");
}
private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
    field.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

    // spacing (WORKS ALWAYS)
    field.setMargin(new java.awt.Insets(0, 10, 0, 0));

    // extra safety padding (BEST FIX)
    field.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        field.getBorder(),
        javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0)
    ));

    field.setText(placeholder);
    field.setForeground(new java.awt.Color(180, 180, 180));

    field.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent e) {
            if (field.getText().equals(placeholder)) {
                field.setText("");
                field.setForeground(new java.awt.Color(30, 30, 30));
            }
        }

        public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getText().isEmpty()) {
                field.setText(placeholder);
                field.setForeground(new java.awt.Color(180, 180, 180));
            }
        }
    });
}
private void addPasswordPlaceholder(javax.swing.JPasswordField field, String placeholder) {
    field.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));

    // ✅ SAME LEFT PADDING
    field.setMargin(new java.awt.Insets(0, 10, 0, 0));

    field.setText(placeholder);
    field.setForeground(new java.awt.Color(180, 180, 180));

    field.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent e) {
            if (String.valueOf(field.getPassword()).equals(placeholder)) {
                field.setText("");
                field.setForeground(new java.awt.Color(30, 30, 30));
            }
        }

        public void focusLost(java.awt.event.FocusEvent e) {
            if (field.getPassword().length == 0) {
                field.setText(placeholder);
                field.setForeground(new java.awt.Color(180, 180, 180));
            }
        }
    });
}
}
