/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author rohanbudha
 */
public class ViewStudentProfile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewStudentProfile.class.getName());

    /**
     * Creates new form ViewStudentProfile
     */
    public ViewStudentProfile() {
        initComponents();
        setLocationRelativeTo(null); // Center the window on the screen
        
        // Connect Edit Profile button to EditPersonalDetails
        jButton1.addActionListener(e -> {
            new EditPersonalDetails().setVisible(true);
            this.dispose();
        });
        
        addPlaceholders();
    }

    private void addPlaceholders() {
        addPlaceholder(jTextField1, "Enter student ID");
        addPlaceholder(jTextField2, "Enter full name");
        addPlaceholder(jTextField3, "Enter your email");
        addPlaceholder(jTextField4, "Enter your program");
        addPlaceholder(jTextField5, "Enter your year level");
        addPlaceholder(jTextField6, "Enter your courses");
        addPlaceholder(jTextField7, "Enter your address");
    }

    private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
        field.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        field.setText(placeholder);
        field.setForeground(new java.awt.Color(180, 180, 180));
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                    field.setForeground(new java.awt.Color(30, 30, 30));
                }
            }
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().isEmpty()) {
                    field.setText(placeholder);
                    field.setForeground(new java.awt.Color(180, 180, 180));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 720));
        setSize(new java.awt.Dimension(910, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Student Id:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(203, 157, 77, 35);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Full Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(203, 211, 77, 35);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(203, 265, 77, 35);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Program:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(203, 319, 77, 35);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Year Level:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(203, 373, 77, 35);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Courses:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(203, 427, 77, 35);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Address:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(203, 481, 77, 35);

        jTextField1.setText("Enter student ID");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(325, 158, 391, 35);

        jTextField2.setText("Enter full name");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(325, 212, 391, 35);

        jTextField3.setText("Enter your email");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(325, 266, 391, 35);

        jTextField4.setText("Enter your program");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(325, 320, 391, 35);

        jTextField5.setText("Enter your year level");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(325, 374, 391, 35);

        jTextField6.setText("Enter your courses");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(325, 428, 391, 35);

        jTextField7.setText("Enter your address");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(325, 482, 391, 35);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setText("My Profile");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(73, 11, 131, 35);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Edit Profile");
        getContentPane().add(jButton1);
        jButton1.setBounds(203, 584, 121, 35);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 584, 91, 35);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reset");
        getContentPane().add(jButton3);
        jButton3.setBounds(624, 584, 92, 35);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(95, 52, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ProfileP.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(101, 52, 87, 78);

        jLabel11.setBackground(new java.awt.Color(249, 226, 226));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(910, 720));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 910, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewStudentProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
